server:
    port: 8082

spring:
    application:
    name: mall

    datasource:
        url: jdbc:mysql://127.0.0.1:3306/seckill?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: root
        password: SHANG6688
        driver-class-name: com.mysql.jdbc.Driver

    redis:
        host: 127.0.0.1
        port: 6379
        password: 123321

    kafka:
        bootstrap-servers: ip:9092,ip:9093

    lettuce:
        pool:
            max-active: 10
            max-idle: 10
            min-idle: 1
            time-between-eviction-runs: 10s
jackson:
    default-property-inclusion: non_null # JSON?????????
mybatis-plus:
    type-aliases-package: com.seckill.entity # ?????
logging:
    level:
        com.seckill: debug